//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chc.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserList", ReplyAction="http://tempuri.org/IUserService/GetUserListResponse")]
        ChcObjects.User[] GetUserList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserList", ReplyAction="http://tempuri.org/IUserService/GetUserListResponse")]
        System.Threading.Tasks.Task<ChcObjects.User[]> GetUserListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ValidateUserByUsernameAndPassword", ReplyAction="http://tempuri.org/IUserService/ValidateUserByUsernameAndPasswordResponse")]
        ChcObjects.User ValidateUserByUsernameAndPassword(ChcObjects.LoginViewModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ValidateUserByUsernameAndPassword", ReplyAction="http://tempuri.org/IUserService/ValidateUserByUsernameAndPasswordResponse")]
        System.Threading.Tasks.Task<ChcObjects.User> ValidateUserByUsernameAndPasswordAsync(ChcObjects.LoginViewModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetRoles", ReplyAction="http://tempuri.org/IUserService/GetRolesResponse")]
        ChcObjects.Role[] GetRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetRoles", ReplyAction="http://tempuri.org/IUserService/GetRolesResponse")]
        System.Threading.Tasks.Task<ChcObjects.Role[]> GetRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateUser", ReplyAction="http://tempuri.org/IUserService/CreateUserResponse")]
        ChcObjects.User CreateUser(ChcObjects.User user, int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateUser", ReplyAction="http://tempuri.org/IUserService/CreateUserResponse")]
        System.Threading.Tasks.Task<ChcObjects.User> CreateUserAsync(ChcObjects.User user, int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        ChcObjects.User UpdateUser(ChcObjects.User user, int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        System.Threading.Tasks.Task<ChcObjects.User> UpdateUserAsync(ChcObjects.User user, int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserAudit", ReplyAction="http://tempuri.org/IUserService/GetUserAuditResponse")]
        ChcObjects.UserAudit[] GetUserAudit(ChcObjects.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserAudit", ReplyAction="http://tempuri.org/IUserService/GetUserAuditResponse")]
        System.Threading.Tasks.Task<ChcObjects.UserAudit[]> GetUserAuditAsync(ChcObjects.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByID", ReplyAction="http://tempuri.org/IUserService/GetUserByIDResponse")]
        ChcObjects.User GetUserByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByID", ReplyAction="http://tempuri.org/IUserService/GetUserByIDResponse")]
        System.Threading.Tasks.Task<ChcObjects.User> GetUserByIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Chc.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<Chc.UserService.IUserService>, Chc.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ChcObjects.User[] GetUserList() {
            return base.Channel.GetUserList();
        }
        
        public System.Threading.Tasks.Task<ChcObjects.User[]> GetUserListAsync() {
            return base.Channel.GetUserListAsync();
        }
        
        public ChcObjects.User ValidateUserByUsernameAndPassword(ChcObjects.LoginViewModel user) {
            return base.Channel.ValidateUserByUsernameAndPassword(user);
        }
        
        public System.Threading.Tasks.Task<ChcObjects.User> ValidateUserByUsernameAndPasswordAsync(ChcObjects.LoginViewModel user) {
            return base.Channel.ValidateUserByUsernameAndPasswordAsync(user);
        }
        
        public ChcObjects.Role[] GetRoles() {
            return base.Channel.GetRoles();
        }
        
        public System.Threading.Tasks.Task<ChcObjects.Role[]> GetRolesAsync() {
            return base.Channel.GetRolesAsync();
        }
        
        public ChcObjects.User CreateUser(ChcObjects.User user, int userid) {
            return base.Channel.CreateUser(user, userid);
        }
        
        public System.Threading.Tasks.Task<ChcObjects.User> CreateUserAsync(ChcObjects.User user, int userid) {
            return base.Channel.CreateUserAsync(user, userid);
        }
        
        public ChcObjects.User UpdateUser(ChcObjects.User user, int userid) {
            return base.Channel.UpdateUser(user, userid);
        }
        
        public System.Threading.Tasks.Task<ChcObjects.User> UpdateUserAsync(ChcObjects.User user, int userid) {
            return base.Channel.UpdateUserAsync(user, userid);
        }
        
        public ChcObjects.UserAudit[] GetUserAudit(ChcObjects.User user) {
            return base.Channel.GetUserAudit(user);
        }
        
        public System.Threading.Tasks.Task<ChcObjects.UserAudit[]> GetUserAuditAsync(ChcObjects.User user) {
            return base.Channel.GetUserAuditAsync(user);
        }
        
        public ChcObjects.User GetUserByID(int id) {
            return base.Channel.GetUserByID(id);
        }
        
        public System.Threading.Tasks.Task<ChcObjects.User> GetUserByIDAsync(int id) {
            return base.Channel.GetUserByIDAsync(id);
        }
    }
}
