//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chc.SiteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SiteService.ISiteService")]
    public interface ISiteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/GetSICLookups", ReplyAction="http://tempuri.org/ISiteService/GetSICLookupsResponse")]
        ChcObjects.SICLookup[] GetSICLookups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/GetSICLookups", ReplyAction="http://tempuri.org/ISiteService/GetSICLookupsResponse")]
        System.Threading.Tasks.Task<ChcObjects.SICLookup[]> GetSICLookupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/GetSICById", ReplyAction="http://tempuri.org/ISiteService/GetSICByIdResponse")]
        ChcObjects.SICLookup GetSICById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/GetSICById", ReplyAction="http://tempuri.org/ISiteService/GetSICByIdResponse")]
        System.Threading.Tasks.Task<ChcObjects.SICLookup> GetSICByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/GetSites", ReplyAction="http://tempuri.org/ISiteService/GetSitesResponse")]
        ChcObjects.Site[] GetSites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/GetSites", ReplyAction="http://tempuri.org/ISiteService/GetSitesResponse")]
        System.Threading.Tasks.Task<ChcObjects.Site[]> GetSitesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/GetSiteById", ReplyAction="http://tempuri.org/ISiteService/GetSiteByIdResponse")]
        ChcObjects.Site GetSiteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/GetSiteById", ReplyAction="http://tempuri.org/ISiteService/GetSiteByIdResponse")]
        System.Threading.Tasks.Task<ChcObjects.Site> GetSiteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/CreateSite", ReplyAction="http://tempuri.org/ISiteService/CreateSiteResponse")]
        ChcObjects.Site CreateSite(ChcObjects.Site site, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/CreateSite", ReplyAction="http://tempuri.org/ISiteService/CreateSiteResponse")]
        System.Threading.Tasks.Task<ChcObjects.Site> CreateSiteAsync(ChcObjects.Site site, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/UpdateSite", ReplyAction="http://tempuri.org/ISiteService/UpdateSiteResponse")]
        ChcObjects.Site UpdateSite(ChcObjects.Site site, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/UpdateSite", ReplyAction="http://tempuri.org/ISiteService/UpdateSiteResponse")]
        System.Threading.Tasks.Task<ChcObjects.Site> UpdateSiteAsync(ChcObjects.Site site, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/GetSiteAudit", ReplyAction="http://tempuri.org/ISiteService/GetSiteAuditResponse")]
        ChcObjects.SiteAudit[] GetSiteAudit(ChcObjects.Site site);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/GetSiteAudit", ReplyAction="http://tempuri.org/ISiteService/GetSiteAuditResponse")]
        System.Threading.Tasks.Task<ChcObjects.SiteAudit[]> GetSiteAuditAsync(ChcObjects.Site site);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISiteServiceChannel : Chc.SiteService.ISiteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiteServiceClient : System.ServiceModel.ClientBase<Chc.SiteService.ISiteService>, Chc.SiteService.ISiteService {
        
        public SiteServiceClient() {
        }
        
        public SiteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ChcObjects.SICLookup[] GetSICLookups() {
            return base.Channel.GetSICLookups();
        }
        
        public System.Threading.Tasks.Task<ChcObjects.SICLookup[]> GetSICLookupsAsync() {
            return base.Channel.GetSICLookupsAsync();
        }
        
        public ChcObjects.SICLookup GetSICById(int id) {
            return base.Channel.GetSICById(id);
        }
        
        public System.Threading.Tasks.Task<ChcObjects.SICLookup> GetSICByIdAsync(int id) {
            return base.Channel.GetSICByIdAsync(id);
        }
        
        public ChcObjects.Site[] GetSites() {
            return base.Channel.GetSites();
        }
        
        public System.Threading.Tasks.Task<ChcObjects.Site[]> GetSitesAsync() {
            return base.Channel.GetSitesAsync();
        }
        
        public ChcObjects.Site GetSiteById(int id) {
            return base.Channel.GetSiteById(id);
        }
        
        public System.Threading.Tasks.Task<ChcObjects.Site> GetSiteByIdAsync(int id) {
            return base.Channel.GetSiteByIdAsync(id);
        }
        
        public ChcObjects.Site CreateSite(ChcObjects.Site site, int userId) {
            return base.Channel.CreateSite(site, userId);
        }
        
        public System.Threading.Tasks.Task<ChcObjects.Site> CreateSiteAsync(ChcObjects.Site site, int userId) {
            return base.Channel.CreateSiteAsync(site, userId);
        }
        
        public ChcObjects.Site UpdateSite(ChcObjects.Site site, int userId) {
            return base.Channel.UpdateSite(site, userId);
        }
        
        public System.Threading.Tasks.Task<ChcObjects.Site> UpdateSiteAsync(ChcObjects.Site site, int userId) {
            return base.Channel.UpdateSiteAsync(site, userId);
        }
        
        public ChcObjects.SiteAudit[] GetSiteAudit(ChcObjects.Site site) {
            return base.Channel.GetSiteAudit(site);
        }
        
        public System.Threading.Tasks.Task<ChcObjects.SiteAudit[]> GetSiteAuditAsync(ChcObjects.Site site) {
            return base.Channel.GetSiteAuditAsync(site);
        }
    }
}
