//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChcDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBooking
    {
        public int BookingID { get; set; }
        public int SiteID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<decimal> InPrice { get; set; }
        public Nullable<decimal> OutPrice { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public bool Deleted { get; set; }
    
        public virtual tblService tblService { get; set; }
        public virtual tblSite tblSite { get; set; }
    }
}
