//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChcDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSiteAudit
    {
        public int SiteAuditID { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public string Event { get; set; }
        public int UserID { get; set; }
        public int SiteID { get; set; }
    
        public virtual tblSite tblSite { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
