//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChcDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSite()
        {
            this.tblSiteAudits = new HashSet<tblSiteAudit>();
        }
    
        public int SiteID { get; set; }
        public string SiteName { get; set; }
        public string Address { get; set; }
        public int SICcode { get; set; }
        public string ContactDetails { get; set; }
        public string ActionDetails { get; set; }
        public bool Deleted { get; set; }
    
        public virtual tblSICLookup tblSICLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSiteAudit> tblSiteAudits { get; set; }
    }
}
