//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChcDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblService
    {
        public int ServiceID { get; set; }
        public int SiteID { get; set; }
        public System.DateTime StartDate { get; set; }
        public int ContractNumber { get; set; }
        public int ContainerID { get; set; }
        public string EWC { get; set; }
        public int ScheduleFrequencyID { get; set; }
        public int ScheduleDay { get; set; }
        public decimal InPrice { get; set; }
        public decimal OutPrice { get; set; }
        public int CarrierID { get; set; }
        public int DisposalLocationID { get; set; }
        public bool IsRecurring { get; set; }
    
        public virtual tblCarrier tblCarrier { get; set; }
        public virtual tblContainer tblContainer { get; set; }
        public virtual tblDisposalLocation tblDisposalLocation { get; set; }
        public virtual tblScheduleFrequency tblScheduleFrequency { get; set; }
        public virtual tblSite tblSite { get; set; }
        public virtual tblEWC tblEWC { get; set; }
    }
}
